parameters:
#    forum_user.example.class: Forum\UserBundle\Example

services:
#    forum_user.example:
#        class: %forum_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
