parameters:
#    forum_forum.example.class: Forum\ForumBundle\Example

services:
#    forum_forum.example:
#        class: %forum_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
